@startuml
package "BusinessApp" {
[Socket] -> [Worker]
[Worker] --> [Socket]
}
tcp - [Socket]

package "BinServlet" {
[Worker] -> [BinServlet]
[BinServlet] --> [Worker]

[BinServlet] -> [FilterChainProcessor]
[FilterChainProcessor] --> [BinServlet]

[FilterChainProcessor] -> [DispatcherServlet]
[DispatcherServlet] --> [FilterChainProcessor]

[DispatcherServlet] -> [HandlerChain]
[HandlerChain] --> [DispatcherServlet]

[DispatcherServlet] -> [HandlerAdapter]
[HandlerAdapter] -> [DispatcherServlet]

[DispatcherServlet] -> [ExceptionResolver]
[ExceptionResolver] --> [DispatcherServlet]

}
@enduml